### ISSUE TITLE
How to add property description

### ISSUE THREAD

**Issue by PureSpider** [ZenHarbinger/l2fprod-properties-editor#10]
The property editor sheet has a description area but I have no idea how to actually get a description for the properties set up. Can you help?

**Comment by ZenHarbinger** [comment]
I'll take a look at it in a couple days.  I haven't used that portion of the code before.

Thanks.

**Comment by ZenHarbinger** [comment]
I'll have to take a go at this over time.  The old code I used/adopted uses naming conventions to create a resource bundle with the values in the properties.
I'll try to see if I can do something with attributes instead.

**Comment by ZenHarbinger** [comment]
OK, I have a solution, I'll check it in and then send it up to maven shortly.
The [l2fprod-common-annotations](https://github.com/ZenHarbinger/l2fprod-common-annotations) project is updated to 1.2.0 w/ annotations for Description and DisplayName, set these values on either the get or set method for the property and they will be read out and put into the control.

Ex: https://github.com/ZenHarbinger/l2fprod-properties-editor/blob/master/src/main/java/com/l2fprod/common/demo/PropertySheetPage.java

**Comment by PureSpider** [comment]
Fantastic! Thank you very much!

**Comment by ZenHarbinger** [comment]
Release to maven, let me know if there are any problems.
