### ISSUE TITLE
Font selection renders with font selection scrolled half way off the table row. Window 10

### ISSUE THREAD

**Issue by tonybeckett** [ZenHarbinger/l2fprod-properties-editor#2]
When selecting the table entry for fonts, the three selection buttons appear but are shifted down by half a row. You only see the top half in the entry. They do work.

**Comment by tonybeckett** [comment]
![Uploading fontissue.PNG…]()

**Comment by tonybeckett** [comment]
![fontissue](https://cloud.githubusercontent.com/assets/7050572/13797993/1f3ce13a-eae8-11e5-9e02-84acfae70681.JPG)

**Comment by ZenHarbinger** [comment]
Legacy from before I adopted the code.  I don't know where this was being created/rendered.  I just updated this to be a combo box dropdown using all fonts (see previous issue).

OK, I have branched off a 1.0.4 that has a FontPropertiesEditor.java file:
https://github.com/ZenHarbinger/l2fprod-properties-editor/blob/1.0.4/src/main/java/com/l2fprod/common/beans/editor/FontPropertyEditor.java

Works, except that when it updates the button live, the font size is set to 1.

**Comment by ZenHarbinger** [comment]
Yes, this was the same for me.  But the editor was being pulled from deep w/in the sun packages.
So I just redid the editor/renderer.  See previously closed issue.

> The default editor/render for Fonts was using a bean in the sun package that was buried pretty deeply.
> There was no way to fix this, so I just replaced it w/ a new Renderer and Editor class.
> I removed the 1.0.4 branch and have put updated sources directly into the master branch.

Thanks.
